FROM    node:8-alpine

ENV     NODE_CONFIG_DIR '/app/config'

RUN     mkdir -p /app/config && mkdir -p /app/ui && mkdir -p /app/src && mkdir -p /app/node_modules

ADD    ./config /app/config/
ADD    ./ui /app/ui/
ADD    ./src /app/src
ADD    ./package.json /app
ADD    ./node_modules /node_modules

#RUN     cd /app && npm install --production

EXPOSE 8080
EXPOSE 8443

CMD     ["node", "/app/src/Buckle.js"]
